version: '3.8'
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - '5432:5432'
    volumes:
      - ./pokeapi/data/v2/csv:/var/lib/pokeapi
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local